version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run: python --version

  validate_terraform_templates:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - run: sudo apt-get update && sudo apt-get install terraform
      - run: terraform version

  unit_test:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: docker -v
      - run: echo $ENCODED_TF_CREDENTIALS

workflows:
  build_and_deploy_infra:
    jobs:
      - validate_terraform_templates
      - unit_test
      - build:
          requires:
            - validate_terraform_templates
            - unit_test

