version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run: python --version
  validate_terraform_templates:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: echo "validate terraform"
  fake_test:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: echo "fake test"

workflows:
  # Name the workflow "welcome"
  build_and_deploy_infra:
    # Run the welcome/run job in its own container
    jobs:
      - validate_terraform_templates
      - fake_test
      - build:
          requires:
            - validate_terraform_templates
            - fake_test

