version: 2.1

#commands:
#  set_terraform_credentials:
#    steps:
#      - run:
#          name: set terraform credentials
#          commands: |
#            mkdir ../.terraform.d
#            echo $ENCODED_TF_CREDENTIALS | base64 -d > ../.terraform.d/credentials.tfrc.json

jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run: echo "build"

  validate_terraform_templates:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: set terraform credentials
          command: |
            mkdir ../.terraform.d
            echo $ENCODED_TF_CREDENTIALS | base64 -d > ../.terraform.d/credentials.tfrc.json
#    persist_to_workspace:
#      root: ..
#      paths:
#        - .terraform.d/credentials.tfrc.json


  unit_test:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: docker -v

workflows:
  build_and_deploy_infra:
    jobs:
      - validate_terraform_templates
      - unit_test
      - build:
          requires:
            - validate_terraform_templates
            - unit_test

